# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocketProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SocketProject
pod 'CocoaAsyncSocket', '~> 7.6.3'
  target 'SocketProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SocketProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
